version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USER:-user}/tuna-backend:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tuna-network
    restart: unless-stopped

  frontend:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USER:-user}/tuna-frontend:${TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tuna-network
    restart: unless-stopped

networks:
  tuna-network:
    driver: bridge
