name: deploy github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: cd app && npm ci

    - name: Build site
      run: cd app && npm run build

    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: app/build
        cname: yao.xlabs.club
